<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Leave Request Application</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333">

    <h2>Leave Request Application</h2>

    <p>Dear Admin,</p>

    <p>
        A leave request has been generated by {{$employee_mail}}.
    </p>

    <p>
        <strong>Leave Type:</strong> {{ $leave->leave_type ?? '-' }}<br>
        <strong>Total Days:</strong> {{ $leave->total_days ?? '-' }}<br>
        @if(!empty($leave->time))
        <strong>Time:</strong> {{ $leave->time ?? '-' }}<br>
        @endif
        <strong>Application Date:</strong> {{ now()->format('d M Y') }}<br>
        <strong>Start Date:</strong> {{ $leave->start_date?->format('d M Y') ?? '-' }}<br>
        <strong>End Date:</strong> {{ $leave->end_date?->format('d M Y') ?? '-' }}
    </p>

    @if(!empty($leave->reason))
        <p>
            <strong>Reason:</strong><br>
            {{ $leave->reason }}
        </p>
    @endif

    <p>
        If you have any questions, please contact the employee at {{$employee_mail}}.
    </p>

    <p>
        Regards,<br>
        HR Department
    </p>

</body>
</html>
